### ISSUE TITLE
7.2 support

### ISSUE THREAD

**Issue by DTEnigma** [BrianHanke/lentil-bhgc#1]
Hi Brian,
Are you planning on updating the code to support 7.2 or is it outside your scope ?

**Comment by BrianHanke** [comment]
@DTEnigma Sadly it's a complex job and would need somebody who is an expert on the code. I think probably only the original dev can do it...

**Comment by BrianHanke** [comment]
Forget I said that, might be working on 7.2. Check out the releases and give it a try!

**Comment by DTEnigma** [comment]
Thanks a lot, will try!
