### ISSUE TITLE
3ds Max support

### ISSUE THREAD

**Issue by NTKKS** [BrianHanke/lentil-bhgc#3]
Have you by any chance tried lentil with 3ds Max? 
I can only see the lentil imager but there is no lentil options in camera like in other DCCs.

**Comment by BrianHanke** [comment]
I haven't tried it since I don't have 3ds Max. But I think it would need a custom UI file to create the camera interface, like Maya has lentilTemplate.py. The original Lentil didn't have that. I'll look into how easy it would be to add it, stay tuned!

**Comment by NTKKS** [comment]
I know there are maxscripts for Arnold here: C:\ProgramData\Autodesk\ApplicationPlugins\MAXtoA_2024\maxscript
These are for special arnold camera types so maybe that can help?
There is also a MAXtoA_SDK and MAXtoA_ui folders

**Comment by BrianHanke** [comment]
Thanks, I'll look into it.

**Comment by BrianHanke** [comment]
Studied this a bit more. The Lentil imager and operator seem to be loading fine, so it's a matter of writing a script for a custom camera UI in 3ds Max. Should be doable. Well... it's on the roadmap!

**Comment by NTKKS** [comment]
Hi, looking through the docs I also found this:
https://help.autodesk.com/view/ARNOL/ENU/?guid=arnold_for_3ds_max_ax_technical_ax_extending_maxtoa_html

**Comment by BrianHanke** [comment]
@NTKKS I've got it working in 3ds Max! Will be adding full support in the next commercial release of Lentil-BHGC. Hoping to get it out before the end of January.

![3dsmax](https://github.com/BrianHanke/lentil-bhgc/assets/59420805/28cb6adb-c85f-4e34-91f5-cdbd01ead04f)
